body:
  - type: dropdown
    attributes:
      name: api_name
      label: Service
      defaultValue: TinyURL
      options:
        - TinyURL
        - CleanURI
        - Spoo.me
  - type: checkbox
    attributes:
      name: sound
      label: Sound notify
      description: Sound notification when link is ready
      defaultValue: 'true'
  - type: checkbox
    attributes:
      name: win_msg
      label: windows message
      description: Show a Windows message when link is ready
      defaultValue: 'true'